version: '3.1'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes: 
      - .:/app
    environment:
      - FLASK_APP=run.py
    command: '/bin/bash entrypoint.sh'
    links: 
      - db
  db:
    image: mysql:8.0
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: passsword
      MYSQL_DATABASE: main_db

    


 